#este archivo es para que Spring haga por defecto lo de la app


server.port=8090

#Spring data JPA y la cofiguración
spring.datasource.url=jdbc:postgresql://localhost:5432/platzi-play_db
spring.datasource.username=dani
spring.datasource.password=2727


# Configuración de LangChain4j
langchain4j.open-ai.chat-model.api-key=demo
#log-requests=true: Muestra en tu consola de IntelliJ exactamente qué le estás enviando a la IA
langchain4j.open-ai.chat-model.log-requests=true
#log-responses=true: Muestra qué te contestó la IA, cuántos "tokens" usó y si hubo algún error.
langchain4j.open-ai.chat-model.log-responses=true

logging.level.dev.langchain4j=DEBUG
logging.level.dev.ai4j.openai4j=DEBUG
