# Conexión Base a PostgreSQL en Render (La nube)
postgresql://daniela:F4N0sI0AjIl0ji1RjwTJT5yN3Ns0lNht@dpg-d8ac6bojs32c739un800-a/platzi_play_db_r057
spring.datasource.url=jdbc:postgresql://dpg-d8ac6bojs32c739un800-a/platzi_play_db_r057?sslmode=require
spring.datasource.username=daniela
spring.datasource.password=F4N0sI0AjIl0ji1RjwTJT5yN3Ns0lNht

spring.jpa.hibernate.ddl-auto=update

# En producción no ejecutamos scripts automáticos para evitar duplicados
spring.sql.init.mode=never

# LangChain4j Producción
langChain4j.open.ai.chat-model.api-key=demo